---
server:
  port: 8090
#  contextPath: /api
# security:
#  user:
#    name: admin
#    password: admin
    
# metro

spring:
  jpa:
    hibernate.ddl-auto: false
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/personas
    username: root
    password: wyvernx02
logging:
  level:
    netgloo: info
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %cyan([%thread]) %green(%-5level) %logger.%M - %msg%n'
name: Hola Mundo MySQL
jwt:
  secret: SecretKeyToGenJWTs
  expiration: 8600_000
  prefix: 'Bearer '
  header: Authorization
  sign: /users